from fastapi import APIRouter

from app.api.routes import audit, auth, cases, claims, checklists, court_arbitr, court_import, court_submission, dashboard, documents, employees, export, external_court_cases, extraction, fns, health, integration_approvals, integration_logs, integration_readiness, organizations, pilot_feedback, pilot_metrics, postal_dispatches, powers_of_attorney, pretensions, rag, russian_post, sandbox_pilot, settings, signatories, system, users, workflow

api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(system.router)
api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(cases.router)
api_router.include_router(organizations.router)
api_router.include_router(fns.router)
api_router.include_router(employees.router)
api_router.include_router(signatories.router)
api_router.include_router(powers_of_attorney.router)
api_router.include_router(postal_dispatches.router)
api_router.include_router(russian_post.router)
api_router.include_router(integration_logs.router)
api_router.include_router(integration_approvals.router)
api_router.include_router(integration_readiness.router)
api_router.include_router(court_arbitr.router)
api_router.include_router(court_import.router)
api_router.include_router(external_court_cases.router)
api_router.include_router(court_submission.router)
api_router.include_router(documents.router)
api_router.include_router(extraction.router)
api_router.include_router(rag.router)
api_router.include_router(pretensions.router)
api_router.include_router(claims.router)
api_router.include_router(checklists.router)
api_router.include_router(workflow.router)
api_router.include_router(audit.router)
api_router.include_router(dashboard.router)
api_router.include_router(pilot_feedback.router)
api_router.include_router(pilot_metrics.router)
api_router.include_router(sandbox_pilot.router)
api_router.include_router(export.router)
api_router.include_router(settings.router)
