import type {
  AuditEntry,
  CaseDetailModel,
  CaseSummary,
  CourtImportJob,
  ExternalCourtCase,
  FnsLookupLog,
  IntegrationRequestLog,
  IntegrationApproval,
  IntegrationCredentialsStatus,
  Organization,
  OrganizationSnapshot,
  PilotCaseMetrics,
  PilotFeedback,
  PilotMetricsSummary,
  PilotReport,
  PilotTimelineEvent,
  PostalDispatch,
  PostalProofCheck,
  PowerOfAttorney,
  RagCitation,
  Role,
  SandboxReadiness,
  SettingItem,
  Signatory,
  SignatoryAuthorityCheck,
  SystemStatus,
  UserProfile,
  Employee,
} from "./types";

const now = new Date().toISOString();

export const mockUsers: Record<Role, UserProfile> = {
  initiator: { id: "u1", email: "initiator@example.com", role: "initiator" },
  lawyer: { id: "u2", email: "lawyer@example.com", role: "lawyer" },
  manager: { id: "u3", email: "manager@example.com", role: "manager" },
  admin: { id: "u4", email: "admin@example.com", role: "admin" },
  service_agent: { id: "u5", email: "service-agent@example.com", role: "service_agent" },
};

export const mockOrganizations: Organization[] = [
  {
    id: "org-1",
    inn: "7701234567",
    kpp: "770101001",
    shortName: "OOO Alpha",
    fullName: "Obshchestvo s ogranichennoy otvetstvennostyu Alpha",
    ogrn: "1027700123456",
    legalAddress: "Moscow, Demo street, 1",
    currentDirectorName: "Ivanov I.I.",
    currentDirectorPosition: "General Director",
    reviewStatus: "VERIFIED",
    source: "MOCK_FNS_PROVIDER",
    actualAt: now,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockOrganizationSnapshots: Record<string, OrganizationSnapshot[]> = {
  "org-1": [
    {
      id: "snap-1",
      source: "MOCK_FNS_PROVIDER",
      actualAt: now,
      rawPayload: '{"inn":"7701234567","kpp":"770101001","director_name":"Ivanov I.I."}',
      createdAt: now,
    },
  ],
};

export const mockFnsLookupLogs: Record<string, FnsLookupLog[]> = {
  "org-1": [
    {
      id: "lookup-1",
      organizationId: "org-1",
      inn: "7701234567",
      providerMode: "MOCK_FOR_DEV",
      source: "MOCK_FNS_PROVIDER",
      reviewStatus: "VERIFIED",
      requestPayload: '{"inn":"7701234567"}',
      responsePayload: '{"short_name":"OOO Alpha"}',
      createdAt: now,
    },
  ],
};

export const mockEmployees: Record<string, Employee[]> = {
  "org-1": [
    {
      id: "emp-1",
      organizationId: "org-1",
      userId: null,
      fullName: "Ivanov I.I.",
      position: "General Director",
      email: "director@example.com",
      isActive: true,
      createdAt: now,
    },
    {
      id: "emp-2",
      organizationId: "org-1",
      userId: "u2",
      fullName: "Petrov P.P.",
      position: "Lawyer",
      email: "lawyer@example.com",
      isActive: true,
      createdAt: now,
    },
  ],
};

export const mockSignatories: Record<string, Signatory[]> = {
  "org-1": [
    {
      id: "sig-1",
      organizationId: "org-1",
      employeeId: "emp-1",
      signatoryType: "DIRECTOR",
      fullName: "Ivanov I.I.",
      authorityBasis: "FNS_DIRECTOR",
      isActive: true,
      createdAt: now,
    },
    {
      id: "sig-2",
      organizationId: "org-1",
      employeeId: "emp-2",
      signatoryType: "AUTHORIZED_EMPLOYEE",
      fullName: "Petrov P.P.",
      authorityBasis: "POWER_OF_ATTORNEY",
      isActive: true,
      createdAt: now,
    },
  ],
};

export const mockPowersOfAttorney: Record<string, PowerOfAttorney[]> = {
  "emp-2": [
    {
      id: "poa-1",
      organizationId: "org-1",
      employeeId: "emp-2",
      userId: "u2",
      number: "DEMO-POA-ACTIVE",
      issuedAt: "2026-01-01",
      expiresAt: "2026-12-31",
      filePath: "/mock/poa-active.pdf",
      status: "ACTIVE",
      authorityScope: ["SIGN_PRETENSION", "SIGN_CLAIM", "REPRESENT_IN_COURT"],
      revokedAt: null,
      createdAt: now,
    },
    {
      id: "poa-2",
      organizationId: "org-1",
      employeeId: "emp-2",
      userId: "u2",
      number: "DEMO-POA-EXPIRED",
      issuedAt: "2025-01-01",
      expiresAt: "2025-12-31",
      filePath: "/mock/poa-expired.pdf",
      status: "EXPIRED",
      authorityScope: ["SIGN_CLAIM"],
      revokedAt: null,
      createdAt: now,
    },
    {
      id: "poa-3",
      organizationId: "org-1",
      employeeId: "emp-2",
      userId: "u2",
      number: "DEMO-POA-REVOKED",
      issuedAt: "2026-01-01",
      expiresAt: "2026-12-31",
      filePath: "/mock/poa-revoked.pdf",
      status: "REVOKED",
      authorityScope: ["SIGN_CLAIM"],
      revokedAt: "2026-04-01",
      createdAt: now,
    },
  ],
};

export const mockAuthorityChecks: Record<string, SignatoryAuthorityCheck[]> = {
  "sig-1": [
    {
      id: "check-auth-1",
      signatoryId: "sig-1",
      caseId: "case-1001",
      powerOfAttorneyId: null,
      documentKind: "claim",
      requiredScopes: ["SIGN_CLAIM", "REPRESENT_IN_COURT"],
      result: "PASSED",
      reason: "Director authority confirmed by FNS data.",
      checkedAt: now,
    },
  ],
  "sig-2": [
    {
      id: "check-auth-2",
      signatoryId: "sig-2",
      caseId: "case-1004",
      powerOfAttorneyId: "poa-1",
      documentKind: "claim",
      requiredScopes: ["SIGN_CLAIM", "REPRESENT_IN_COURT"],
      result: "PASSED",
      reason: "Active power of attorney covers all required scopes.",
      checkedAt: now,
    },
    {
      id: "check-auth-3",
      signatoryId: "sig-2",
      caseId: "case-1003",
      powerOfAttorneyId: "poa-2",
      documentKind: "claim",
      requiredScopes: ["SIGN_CLAIM", "REPRESENT_IN_COURT"],
      result: "FAILED",
      reason: "Power of attorney is expired or revoked.",
      checkedAt: now,
    },
  ],
};

export const mockCases: CaseSummary[] = [
  {
    id: "case-1001",
    title: "DEMO-001 director happy path",
    plaintiff: "OOO Alpha",
    defendant: "OOO Beta",
    amount: "1 250 000 RUB",
    status: "COURT_PACKAGE_READY",
    updatedAt: now,
    responsibleLawyer: "lawyer@example.com",
  },
  {
    id: "case-1004",
    title: "DEMO-002 employee happy path",
    plaintiff: "OOO Alpha",
    defendant: "OOO Gamma",
    amount: "2 100 000 RUB",
    status: "COURT_PACKAGE_READY",
    updatedAt: now,
    responsibleLawyer: "lawyer@example.com",
  },
  {
    id: "case-1003",
    title: "DEMO-003 authority block path",
    plaintiff: "OOO Alpha",
    defendant: "OOO Delta",
    amount: "480 000 RUB",
    status: "LAWYER_REVIEW",
    updatedAt: now,
    responsibleLawyer: "lawyer@example.com",
  },
];

const citations001: RagCitation[] = [
  {
    id: "cit-1",
    sourceId: "src-1",
    caseId: "case-1001",
    targetType: "claim",
    targetId: "claim-1",
    quote: "Send a copy of the claim to the respondent before court filing.",
    createdAt: now,
  },
];

const citations002: RagCitation[] = [
  {
    id: "cit-2",
    sourceId: "src-2",
    caseId: "case-1004",
    targetType: "claim",
    targetId: "claim-4",
    quote: "Pretrial procedure must be reflected in the claim package.",
    createdAt: now,
  },
];

export const mockCaseDetails: Record<string, CaseDetailModel> = {
  "case-1001": {
    ...mockCases[0],
    description: "Director signs the claim. All gates are green for export.",
    documents: [
      { id: "doc-1", caseId: "case-1001", fileName: "contract.pdf", mimeType: "application/pdf", sha256: "mock-sha-1", extractedText: "Supply contract No 123/24", approved: true, createdAt: now, status: "parsed" },
      { id: "doc-2", caseId: "case-1001", fileName: "act.pdf", mimeType: "application/pdf", sha256: "mock-sha-2", extractedText: "Acceptance act for 1 250 000 RUB", approved: true, createdAt: now, status: "parsed" },
    ],
    facts: [
      { id: "fact-1", title: "Contract", value: "123/24", confidence: 0.92, source: "contract.pdf" },
      { id: "fact-2", title: "Amount", value: "1 250 000 RUB", confidence: 0.88, source: "act.pdf" },
    ],
    pretension: { id: "pret-1", caseId: "case-1001", content: "Approved pretension for DEMO-001.", approved: true, updatedAt: now },
    claim: { id: "claim-1", caseId: "case-1001", content: "Approved claim signed by director.", approved: true, updatedAt: now },
    checklist: {
      id: "check-1",
      caseId: "case-1001",
      status: "done",
      items: [{ id: "item-1", title: "Court package readiness confirmed", isCompleted: true, notes: "All proofs attached." }],
    },
    citations: citations001,
  },
  "case-1004": {
    ...mockCases[1],
    description: "Employee signs with active POA. Happy path remains exportable.",
    documents: [
      { id: "doc-4", caseId: "case-1004", fileName: "contract.pdf", mimeType: "application/pdf", sha256: "mock-sha-4", extractedText: "Supply contract and debt calculation", approved: true, createdAt: now, status: "parsed" },
      { id: "doc-5", caseId: "case-1004", fileName: "calculation.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sha256: "mock-sha-5", extractedText: "Claim amount calculation", approved: true, createdAt: now, status: "parsed" },
    ],
    facts: [{ id: "fact-4", title: "Amount", value: "2 100 000 RUB", confidence: 0.96, source: "calculation.xlsx" }],
    pretension: { id: "pret-4", caseId: "case-1004", content: "Approved pretension for DEMO-002.", approved: true, updatedAt: now },
    claim: { id: "claim-4", caseId: "case-1004", content: "Approved claim with employee signatory and POA.", approved: true, updatedAt: now },
    checklist: {
      id: "check-4",
      caseId: "case-1004",
      status: "done",
      items: [{ id: "item-4", title: "Claim copy proof checked", isCompleted: true, notes: "Delivery proof available." }],
    },
    citations: citations002,
  },
  "case-1003": {
    ...mockCases[2],
    description: "Negative scenario: expired or revoked authority must block approval and export.",
    documents: [
      { id: "doc-3", caseId: "case-1003", fileName: "claim-draft.docx", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", sha256: "mock-sha-3", extractedText: "Claim draft", approved: true, createdAt: now, status: "parsed" },
    ],
    facts: [{ id: "fact-3", title: "Amount", value: "480 000 RUB", confidence: 0.81, source: "claim-draft.docx" }],
    pretension: { id: "pret-3", caseId: "case-1003", content: "Pretension is approved but authority is no longer valid.", approved: true, updatedAt: now },
    claim: { id: "claim-3", caseId: "case-1003", content: "Claim cannot be approved because the POA is invalid.", approved: false, updatedAt: now },
    checklist: {
      id: "check-3",
      caseId: "case-1003",
      status: "open",
      items: [{ id: "item-3", title: "Authority issue must be resolved", isCompleted: false, notes: "Expired or revoked POA." }],
    },
    citations: [],
  },
};

export const mockPostalDispatches: PostalDispatch[] = [
  {
    id: "dispatch-pret-1",
    caseId: "case-1001",
    organizationId: "org-1",
    dispatchKind: "pretension",
    providerMode: "MOCK_FOR_DEV",
    recipientName: "OOO Beta",
    recipientAddress: "Moscow, Respondent street, 7",
    status: "DELIVERED",
    trackingNumber: "RP0001",
    externalDispatchId: "dispatch-ext-1",
    source: "MOCK_RUSSIAN_POST",
    statusPayload: '{"status":"DELIVERED"}',
    createdById: "u2",
    createdAt: now,
  },
  {
    id: "dispatch-claim-1",
    caseId: "case-1001",
    organizationId: "org-1",
    dispatchKind: "claim_copy",
    providerMode: "MOCK_FOR_DEV",
    recipientName: "OOO Beta",
    recipientAddress: "Moscow, Respondent street, 7",
    status: "DELIVERED",
    trackingNumber: "RP0002",
    externalDispatchId: "dispatch-ext-2",
    source: "MOCK_RUSSIAN_POST",
    statusPayload: '{"status":"DELIVERED"}',
    createdById: "u2",
    createdAt: now,
  },
  {
    id: "dispatch-pret-2",
    caseId: "case-1004",
    organizationId: "org-1",
    dispatchKind: "pretension",
    providerMode: "MOCK_FOR_DEV",
    recipientName: "OOO Gamma",
    recipientAddress: "Moscow, Recipient avenue, 2",
    status: "DELIVERED",
    trackingNumber: "RP0003",
    externalDispatchId: "dispatch-ext-3",
    source: "MOCK_RUSSIAN_POST",
    statusPayload: '{"status":"DELIVERED"}',
    createdById: "u2",
    createdAt: now,
  },
  {
    id: "dispatch-claim-2",
    caseId: "case-1004",
    organizationId: "org-1",
    dispatchKind: "claim_copy",
    providerMode: "MOCK_FOR_DEV",
    recipientName: "OOO Gamma",
    recipientAddress: "Moscow, Recipient avenue, 2",
    status: "DELIVERED",
    trackingNumber: "RP0004",
    externalDispatchId: "dispatch-ext-4",
    source: "MOCK_RUSSIAN_POST",
    statusPayload: '{"status":"DELIVERED"}',
    createdById: "u2",
    createdAt: now,
  },
  {
    id: "dispatch-claim-3",
    caseId: "case-1003",
    organizationId: "org-1",
    dispatchKind: "claim_copy",
    providerMode: "MANUAL_UPLOAD",
    recipientName: "OOO Delta",
    recipientAddress: "Moscow, Defendant road, 9",
    status: "CREATED",
    trackingNumber: "",
    externalDispatchId: "",
    source: "MANUAL_UPLOAD",
    statusPayload: '{"status":"CREATED"}',
    createdById: "u2",
    createdAt: now,
  },
];

export const mockPostalProofChecks: Record<string, PostalProofCheck> = {
  "case-1001": { caseId: "case-1001", hasClaimCopyProof: true, dispatchIds: ["dispatch-claim-1"] },
  "case-1004": { caseId: "case-1004", hasClaimCopyProof: true, dispatchIds: ["dispatch-claim-2"] },
  "case-1003": { caseId: "case-1003", hasClaimCopyProof: false, dispatchIds: ["dispatch-claim-3"] },
};

export const mockCourtImportJobs: CourtImportJob[] = [
  {
    id: "job-1",
    organizationId: "org-1",
    inn: "7701234567",
    dateFrom: "2026-05-01",
    dateTo: "2026-05-31",
    participationRole: "claimant",
    providerMode: "MOCK_FOR_DEV",
    status: "COMPLETED",
    source: "MOCK_COURT_PROVIDER",
    resultCount: 1,
    createdById: "u4",
    createdAt: now,
  },
];

export const mockExternalCourtCases: ExternalCourtCase[] = [
  {
    id: "ext-1",
    importJobId: "job-1",
    organizationId: "org-1",
    externalCaseUid: "kad-001",
    caseNumber: "A40-12345/2026",
    courtName: "Arbitration Court of Moscow",
    participantRole: "claimant",
    claimSubject: "Debt recovery",
    caseDate: "2026-05-15",
    linkedCaseId: "case-1004",
    source: "MOCK_COURT_PROVIDER",
    payloadHash: "mock-payload-hash",
    createdAt: now,
    events: [{ id: "event-1", eventDate: "2026-05-20", eventType: "accepted", description: "Case card created.", createdAt: now }],
    snapshots: [{ id: "snapshot-1", source: "MOCK_COURT_PROVIDER", snapshotPayload: '{"case_number":"A40-12345/2026"}', snapshotHash: "mock-snapshot-hash", createdAt: now }],
  },
];

export const mockSettings: SettingItem[] = [
  { key: "FNS_PROVIDER_MODE", value: "MOCK_FOR_DEV", description: "Mock/manual FNS mode" },
  { key: "ENABLE_FNS_SANDBOX", value: "false", description: "Sandbox FNS integration is disabled" },
  { key: "ENABLE_REAL_FNS", value: "false", description: "Real FNS integration is disabled" },
  { key: "RUSSIAN_POST_MODE", value: "MOCK_FOR_DEV", description: "Mock/manual postal integration mode" },
  { key: "ENABLE_RUSSIAN_POST_SANDBOX", value: "false", description: "Sandbox Russian Post integration is disabled" },
  { key: "ENABLE_REAL_POST_SEND", value: "false", description: "Real post send is disabled" },
  { key: "COURT_PROVIDER_MODE", value: "MOCK_FOR_DEV", description: "Court import provider mode" },
  { key: "ENABLE_COURT_SANDBOX", value: "false", description: "Sandbox court integration is disabled" },
  { key: "ENABLE_REAL_COURT_SEARCH", value: "false", description: "Real court search is disabled" },
  { key: "ENABLE_PUBLIC_KAD_SEARCH", value: "false", description: "Public KAD search is disabled" },
  { key: "ENABLE_COURT_SUBMISSION", value: "false", description: "Court submission is disabled" },
  { key: "LLM_MODEL", value: "stub-openai-compatible", description: "Local stub LLM model" },
  { key: "LLM_API_KEY", value: "[REDACTED]", description: "Masked secret value" },
];

export const mockSystemStatus: SystemStatus = {
  backend: "ok",
  database: "ok",
  storage: "ok",
  redis: "ok",
  worker: "ok",
  vectorDb: "ok",
  llm: "mock",
  fnsProvider: "mock_fns_adapter",
  fnsMode: "MOCK_FOR_DEV",
  fnsSandboxEnabled: false,
  realFnsEnabled: false,
  russianPostProvider: "mock_russian_post_adapter",
  russianPostMode: "MOCK_FOR_DEV",
  russianPostSandboxEnabled: false,
  realPostSendEnabled: false,
  courtArbitrProvider: "mock_court_arbitr_adapter",
  courtArbitrMode: "MOCK_FOR_DEV",
  courtSandboxEnabled: false,
  realCourtSearchEnabled: false,
  publicKadSearchEnabled: false,
  courtSubmissionEnabled: false,
};

export const mockSandboxReadiness: SandboxReadiness = {
  fns: {
    sandboxFlag: false,
    credentialsPresent: false,
    testConnectionStatus: "disabled",
    readyForSandbox: false,
    blockingReasons: ["sandbox_flag_disabled", "sandbox_credentials_missing", "sandbox_approval_requested"],
    mode: "FNS_SANDBOX_DISABLED",
    provider: "sandbox_fns_adapter",
    approvalStatus: "REQUESTED",
    activeApproval: false,
    approvalExpiresAt: null,
  },
  russianPost: {
    sandboxFlag: false,
    credentialsPresent: false,
    testConnectionStatus: "disabled",
    readyForSandbox: false,
    blockingReasons: ["sandbox_flag_disabled", "sandbox_credentials_missing", "sandbox_approval_requested"],
    mode: "RUSSIAN_POST_SANDBOX_DISABLED",
    provider: "sandbox_russian_post_adapter",
    approvalStatus: "REQUESTED",
    activeApproval: false,
    approvalExpiresAt: null,
  },
  court: {
    sandboxFlag: false,
    credentialsPresent: false,
    testConnectionStatus: "disabled",
    readyForSandbox: false,
    blockingReasons: ["sandbox_flag_disabled", "sandbox_credentials_missing", "sandbox_approval_requested"],
    mode: "COURT_SANDBOX_DISABLED",
    provider: "sandbox_court_arbitr_adapter",
    approvalStatus: "REQUESTED",
    activeApproval: false,
    approvalExpiresAt: null,
  },
};

export const mockIntegrationCredentialsStatus: IntegrationCredentialsStatus = {
  fns: {
    sandboxCredentialsPresent: false,
    productionCredentialsPresent: false,
  },
  russianPost: {
    sandboxCredentialsPresent: false,
    productionCredentialsPresent: false,
  },
  courtArbitr: {
    sandboxCredentialsPresent: false,
    productionCredentialsPresent: false,
  },
};

export const mockIntegrationApprovals: IntegrationApproval[] = [
  {
    id: "approval-1",
    integrationName: "FNS",
    environment: "SANDBOX",
    requestedById: "u4",
    approvedById: null,
    status: "REQUESTED",
    reason: "Sandbox lookup validation before credential handoff.",
    approvedAt: null,
    expiresAt: "2026-06-30T12:00:00Z",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "approval-2",
    integrationName: "RUSSIAN_POST",
    environment: "SANDBOX",
    requestedById: "u4",
    approvedById: "u4",
    status: "APPROVED",
    reason: "Postal dry-run checks approved for sandbox validation.",
    approvedAt: now,
    expiresAt: "2026-06-15T12:00:00Z",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "approval-3",
    integrationName: "COURT_ARBITR",
    environment: "PRODUCTION",
    requestedById: "u4",
    approvedById: null,
    status: "REJECTED",
    reason: "Production approvals remain disabled in the current MVP.",
    approvedAt: null,
    expiresAt: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockIntegrationLogs: IntegrationRequestLog[] = [
  {
    id: "ilog-1",
    integrationName: "fns",
    provider: "mock_fns_adapter",
    mode: "MOCK_FOR_DEV",
    operation: "test_connection",
    requestId: "req-fns-1",
    idempotencyKey: "",
    status: "SUCCESS",
    httpStatus: 200,
    startedAt: now,
    finishedAt: now,
    durationMs: 3,
    errorCode: "",
    errorMessage: "",
    safeRequestMetadataJson: '{"real_api_enabled":false}',
    safeResponseMetadataJson: '{"ok":true}',
    createdById: "u4",
    caseId: null,
    organizationId: "org-1",
    createdAt: now,
  },
  {
    id: "ilog-2",
    integrationName: "court_arbitr",
    provider: "mock_court_arbitr_adapter",
    mode: "MOCK_FOR_DEV",
    operation: "import_cases_by_period",
    requestId: "req-court-1",
    idempotencyKey: "court-org1-may",
    status: "SUCCESS",
    httpStatus: 200,
    startedAt: now,
    finishedAt: now,
    durationMs: 5,
    errorCode: "",
    errorMessage: "",
    safeRequestMetadataJson: '{"organization_id":"org-1"}',
    safeResponseMetadataJson: '{"result_count":1}',
    createdById: "u4",
    caseId: "case-1004",
    organizationId: "org-1",
    createdAt: now,
  },
];

export const mockAuditEntries: AuditEntry[] = [
  { id: "audit-1", actorUserId: "u4", action: "organization_created", entityType: "organization", entityId: "org-1", details: "Organization created from mock FNS lookup", requestId: "req-org-1", createdAt: now },
  { id: "audit-2", actorUserId: "u4", action: "power_of_attorney_created", entityType: "power_of_attorney", entityId: "poa-1", details: "POA created for employee emp-2", requestId: "req-poa-1", createdAt: now },
  { id: "audit-3", actorUserId: "u2", action: "claim_approved", entityType: "claim", entityId: "claim-1", details: "Claim approved after authority check", requestId: "req-claim-1", createdAt: now },
  { id: "audit-4", actorUserId: "u2", action: "postal_proof_uploaded", entityType: "postal_dispatch", entityId: "dispatch-claim-1", details: "Proof uploaded for claim copy dispatch", requestId: "req-post-1", createdAt: now },
  { id: "audit-5", actorUserId: "u4", action: "court_import_job_created", entityType: "court_import_job", entityId: "job-1", details: "Mock court import job created for May 2026", requestId: "req-court-1", createdAt: now },
  { id: "audit-6", actorUserId: "u4", action: "setting_updated", entityType: "system_setting", entityId: "LLM_API_KEY", details: "Sensitive setting updated: [REDACTED]", requestId: "req-setting-1", createdAt: now },
  { id: "audit-7", actorUserId: "u2", action: "case_exported", entityType: "export_package", entityId: "case-1001", details: "Court package exported after proof-of-service gate", requestId: "req-export-1", createdAt: now },
  { id: "audit-8", actorUserId: "u2", action: "pilot_feedback_created", entityType: "pilot_feedback", entityId: "feedback-1", details: "Pilot feedback created for DEMO-003 authority block", requestId: "req-feedback-1", createdAt: now },
  { id: "audit-9", actorUserId: "u2", action: "claim_approval_blocked", entityType: "case", entityId: "case-1003", details: "Power of attorney DEMO-POA-EXPIRED is expired", requestId: "req-block-1", createdAt: now },
];

export const mockPilotFeedback: PilotFeedback[] = [
  {
    id: "feedback-1",
    caseId: "case-1003",
    userId: "u2",
    role: "lawyer",
    module: "AUTHORITY",
    severity: "MEDIUM",
    title: "Authority block is visible and expected",
    description: "Negative path remains useful for pilot validation.",
    expectedBehavior: "Approval and export are blocked.",
    actualBehavior: "UI shows blocked authority and export is disabled.",
    screenshotDocumentId: null,
    status: "TRIAGED",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockPilotCaseMetrics: PilotCaseMetrics[] = [
  {
    caseId: "case-1001",
    title: mockCases[0].title,
    status: "COURT_PACKAGE_READY",
    factsReadyMinutes: 8,
    pretensionDraftMinutes: 12,
    pretensionReviewMinutes: 15,
    claimDraftMinutes: 18,
    claimReviewMinutes: 11,
    pretensionEdits: 1,
    claimEdits: 1,
    ragWarnings: 0,
    authorityWarnings: 0,
    authorityInvalids: 0,
    authorityChecksTotal: 1,
    authority: { checksTotal: 1, validCount: 1, warningCount: 0, invalidCount: 0, blockedActionsCount: 0 },
    blockedActions: 0,
    feedbackItems: 0,
    pretensionDraftDataStatus: "ok",
  },
  {
    caseId: "case-1004",
    title: mockCases[1].title,
    status: "COURT_PACKAGE_READY",
    factsReadyMinutes: 7,
    pretensionDraftMinutes: 10,
    pretensionReviewMinutes: 13,
    claimDraftMinutes: 16,
    claimReviewMinutes: 9,
    pretensionEdits: 2,
    claimEdits: 2,
    ragWarnings: 0,
    authorityWarnings: 0,
    authorityInvalids: 0,
    authorityChecksTotal: 1,
    authority: { checksTotal: 1, validCount: 1, warningCount: 0, invalidCount: 0, blockedActionsCount: 0 },
    blockedActions: 0,
    feedbackItems: 0,
    pretensionDraftDataStatus: "ok",
  },
  {
    caseId: "case-1003",
    title: mockCases[2].title,
    status: "LAWYER_REVIEW",
    factsReadyMinutes: 5,
    pretensionDraftMinutes: 9,
    pretensionReviewMinutes: 7,
    claimDraftMinutes: 14,
    claimReviewMinutes: null,
    pretensionEdits: 1,
    claimEdits: 1,
    ragWarnings: 1,
    authorityWarnings: 0,
    authorityInvalids: 1,
    authorityChecksTotal: 1,
    authority: { checksTotal: 1, validCount: 0, warningCount: 0, invalidCount: 1, blockedActionsCount: 1 },
    blockedActions: 1,
    feedbackItems: 1,
    pretensionDraftDataStatus: "ok",
  },
];

export const mockPilotMetricsSummary: PilotMetricsSummary = {
  totalCases: 3,
  completedHappyPathCases: 2,
  blockedCases: 1,
  totalFeedbackItems: 1,
  blockerFeedbackItems: 0,
  highFeedbackItems: 0,
  feedbackBySeverityTotal: { BLOCKER: 1, HIGH: 0, MEDIUM: 1, LOW: 0, IDEA: 0 },
  feedbackBySeverityUnresolved: { BLOCKER: 0, HIGH: 0, MEDIUM: 1, LOW: 0, IDEA: 0 },
  averagePretensionDraftMinutes: 10.33,
  averagePretensionDraftDataStatus: "ok",
  averageClaimDraftMinutes: 16,
  totalRagWarnings: 1,
  totalAuthorityWarnings: 0,
  totalAuthorityInvalids: 1,
  totalAuthorityChecks: 3,
  totalBlockedActions: 1,
  authority: { checksTotal: 3, validCount: 2, warningCount: 0, invalidCount: 1, blockedActionsCount: 1 },
  authorityByCase: [
    { caseId: "case-1001", title: mockCases[0].title, checksTotal: 1, validCount: 1, warningCount: 0, invalidCount: 0, blockedActionsCount: 0 },
    { caseId: "case-1004", title: mockCases[1].title, checksTotal: 1, validCount: 1, warningCount: 0, invalidCount: 0, blockedActionsCount: 0 },
    { caseId: "case-1003", title: mockCases[2].title, checksTotal: 1, validCount: 0, warningCount: 0, invalidCount: 1, blockedActionsCount: 1 },
  ],
  cases: mockPilotCaseMetrics,
};

export const mockPilotReport: PilotReport = {
  period: "internal pilot",
  dateFrom: "2026-05-01",
  dateTo: "2026-05-31",
  totalCases: 3,
  caseStatuses: {
    COURT_PACKAGE_READY: 2,
    LAWYER_REVIEW: 1,
  },
  feedbackTotal: 1,
  feedbackBySeverityTotal: { BLOCKER: 1, HIGH: 0, MEDIUM: 1, LOW: 0, IDEA: 0 },
  feedbackBySeverityUnresolved: { BLOCKER: 0, HIGH: 0, MEDIUM: 1, LOW: 0, IDEA: 0 },
  averagePretensionDraftMinutes: 10.33,
  averagePretensionDraftDataStatus: "ok",
  averageClaimDraftMinutes: 16,
  aiRagWarnings: 1,
  authorityWarnings: 0,
  authorityInvalids: 1,
  authorityChecksTotal: 3,
  blockedActions: 1,
  exportsGenerated: 2,
  exportedCaseIds: ["case-1001", "case-1004"],
  unresolvedItems: [],
  timelineSummary: {
    CASE_CREATED: 3,
    CLAIM_APPROVED: 2,
    AUTHORITY_CHECK_FAILED: 1,
    EXPORT_GENERATED: 2,
  },
  recommendation: "go",
};

export const mockPilotTimelines: Record<string, PilotTimelineEvent[]> = {
  "case-1001": [
    { id: "tl-1", caseId: "case-1001", eventType: "CASE_CREATED", title: "Case created", description: "DEMO-001 director happy path", createdAt: now, actorUserId: "u1", actorRole: "initiator", source: "case", severity: "info", relatedEntityType: "case", relatedEntityId: "case-1001" },
    { id: "tl-2", caseId: "case-1001", eventType: "FACT_EXTRACTION_COMPLETED", title: "Facts extracted", description: "2 facts saved", createdAt: now, actorUserId: "u1", actorRole: "initiator", source: "extracted_fact", severity: "info", relatedEntityType: "case", relatedEntityId: "case-1001" },
    { id: "tl-3", caseId: "case-1001", eventType: "PRETENSION_GENERATED", title: "Pretension generated", description: "Pretension draft is available", createdAt: now, actorUserId: "u2", actorRole: "lawyer", source: "pretension", severity: "info", relatedEntityType: "pretension", relatedEntityId: "pret-1" },
    { id: "tl-4", caseId: "case-1001", eventType: "CLAIM_APPROVED", title: "Claim approved", description: "Claim approved", createdAt: now, actorUserId: "u2", actorRole: "lawyer", source: "workflow", severity: "info", relatedEntityType: "claim", relatedEntityId: "claim-1" },
    { id: "tl-5", caseId: "case-1001", eventType: "EXPORT_GENERATED", title: "Export generated", description: "mock/exports/1001.zip", createdAt: now, actorUserId: "u2", actorRole: "lawyer", source: "export_package", severity: "info", relatedEntityType: "export_package", relatedEntityId: "export-1001" },
  ],
  "case-1004": [
    { id: "tl-6", caseId: "case-1004", eventType: "CASE_CREATED", title: "Case created", description: "DEMO-002 employee happy path", createdAt: now, actorUserId: "u1", actorRole: "initiator", source: "case", severity: "info", relatedEntityType: "case", relatedEntityId: "case-1004" },
    { id: "tl-7", caseId: "case-1004", eventType: "AUTHORITY_CHECK_PASSED", title: "Authority check", description: "Active power of attorney covers all required scopes.", createdAt: now, actorUserId: "u2", actorRole: "lawyer", source: "signatory_authority_check", severity: "info", relatedEntityType: "signatory_authority_check", relatedEntityId: "check-auth-2" },
    { id: "tl-8", caseId: "case-1004", eventType: "EXPORT_GENERATED", title: "Export generated", description: "mock/exports/1004.zip", createdAt: now, actorUserId: "u2", actorRole: "lawyer", source: "export_package", severity: "info", relatedEntityType: "export_package", relatedEntityId: "export-1004" },
  ],
  "case-1003": [
    { id: "tl-9", caseId: "case-1003", eventType: "CASE_CREATED", title: "Case created", description: "DEMO-003 authority block path", createdAt: now, actorUserId: "u1", actorRole: "initiator", source: "case", severity: "info", relatedEntityType: "case", relatedEntityId: "case-1003" },
    { id: "tl-10", caseId: "case-1003", eventType: "AUTHORITY_CHECK_FAILED", title: "Authority check", description: "Power of attorney is expired or revoked.", createdAt: now, actorUserId: "u2", actorRole: "lawyer", source: "signatory_authority_check", severity: "error", relatedEntityType: "signatory_authority_check", relatedEntityId: "check-auth-3" },
    { id: "tl-11", caseId: "case-1003", eventType: "PILOT_FEEDBACK_CREATED", title: "Pilot feedback created", description: "Authority block is visible and expected", createdAt: now, actorUserId: "u2", actorRole: "lawyer", source: "pilot_feedback", severity: "medium", relatedEntityType: "pilot_feedback", relatedEntityId: "feedback-1" },
  ],
};
